# Generated by Django 5.2.4 on 2025-07-24 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('full', 'Full Routine'), ('hydration', 'Hydration Plan'), ('acne', 'Anti-Acne Routine'), ('brightening', 'Brightening Plan'), ('anti_aging', 'Anti-Aging Routine'), ('sensitive', 'Sensitive Skin Routine'), ('minimal', 'Minimal Routine'), ('oily', 'Oily Skin Plan'), ('morning', 'Morning Routine'), ('night', 'Night Routine')], max_length=100)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
