# Generated by Django 5.2.4 on 2025-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineplan',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
