# Generated by Django 5.2.4 on 2025-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_routineplan_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineplan',
            name='generated',
        ),
        migrations.AlterField(
            model_name='routineplan',
            name='plan_name',
            field=models.CharField(choices=[('full', 'Full Routine'), ('hydration', 'Hydration Plan'), ('acne', 'Anti-Acne Routine'), ('brightening', 'Brightening Plan'), ('anti_aging', 'Anti-Aging Routine'), ('sensitive', 'Sensitive Skin Routine'), ('minimal', 'Minimal Routine'), ('oily', 'Oily Skin Plan'), ('morning', 'Morning Routine'), ('night', 'Night Routine')], default='full', max_length=100),
        ),
        migrations.AlterField(
            model_name='routineplan',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
