# Generated by Django 5.2.4 on 2025-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_remove_routineplan_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineplan',
            name='plan_name',
            field=models.CharField(choices=[('full', 'Full Routine'), ('hydration', 'Hydration Plan'), ('mini', 'Minimalist Plan')], default='full', max_length=100),
        ),
    ]
