# Generated by Django 5.2.4 on 2025-07-21 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('single', 'تک\u200cگزینه\u200cای (Radio button)'), ('multiple', 'چندگزینه\u200cای (Checkbox)'), ('range', 'مقدار عددی (Slider)'), ('age_range', 'محدوده سنی (Dropdown)'), ('scale', 'مقیاس 1 تا 5 (Likert scale)'), ('boolean', 'بله / خیر (Yes/No)')], default='single', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('effects', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_choices', models.ManyToManyField(blank=True, to='quiz.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_skipped', models.BooleanField(default=False)),
                ('acne', models.IntegerField(default=0)),
                ('sensitivity', models.IntegerField(default=0)),
                ('dryness', models.IntegerField(default=0)),
                ('oiliness', models.IntegerField(default=0)),
                ('redness', models.IntegerField(default=0)),
                ('age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('hydration', models.IntegerField(default=0)),
                ('elasticity', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
