# Generated by Django 5.2.4 on 2025-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprofile',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('$', 'ارزان'), ('$$', 'متوسط'), ('$$$', 'گران')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'خشک'), ('oily', 'چرب'), ('sensitive', 'حساس'), ('combination', 'مختلط'), ('normal', 'نرمال')], default=5, max_length=20),
            preserve_default=False,
        ),
    ]
