# Generated by Django 5.2.4 on 2025-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_skinprofile_budget_range_skinprofile_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinprofile',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'خشک'), ('oily', 'چرب'), ('sensitive', 'حساس'), ('combination', 'مختلط'), ('normal', 'نرمال')], default='normal', max_length=20),
        ),
    ]
