# Generated by Django 5.2.4 on 2025-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_skinprofile_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
