# Generated by Django 5.2.4 on 2025-07-31 11:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_skinprofile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinprofile',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dry', 'خشک'), ('oily', 'چرب'), ('sensitive', 'حساس'), ('combination', 'مختلط'), ('normal', 'نرمال')], max_length=50),
        ),
    ]
