# Generated by Django 5.2.4 on 2025-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_skinprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='do_not_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='elasticity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='hydration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='sensitivity',
            field=models.IntegerField(default=5),
        ),
    ]
