# Generated by Django 5.2.4 on 2025-08-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_do_not_now_alter_skinprofile_elasticity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('acne', 'Acne'), ('sensivity', 'Sensivity'), ('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('redness', 'Redness'), ('hydration', 'Hydration'), ('elasticity', 'Elasticity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='elasticity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='hydration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='sensitivity',
            field=models.IntegerField(default=0),
        ),
    ]
