# Generated by Django 5.2.4 on 2025-08-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_skinprofile_skin_type'),
        ('quiz', '0006_question_subject_alter_skinprofile_elasticity_and_more'),
    ]

    operations = [
    ]
