# Generated by Django 5.2.4 on 2025-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_productsearchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsearchhistory',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('wishlist', 'Wishlist'), ('cart', 'Cart'), ('purchase', 'Purchase')], max_length=10),
        ),
    ]
