# Generated by Django 5.2.1 on 2025-07-07 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مناسب برای'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='نحوه مصرف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.png', upload_to='product_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('product', 'user')},
        ),
    ]
