# Generated by Django 5.2.1 on 2025-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_product_description_product_suitable_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleanser', 'پاک\u200cکننده'), ('toner', 'تونر'), ('serum', 'سرم'), ('moisturizer', 'مرطوب\u200cکننده'), ('sunscreen', 'ضدآفتاب'), ('eye_cream', 'کرم دور چشم'), ('mask', 'ماسک صورت'), ('exfoliator', 'لایه\u200cبردار'), ('treatment', 'درمان متمرکز'), ('oil', 'روغن صورت'), ('mist', 'اسپری/میست صورت'), ('lip_care', 'مراقبت لب'), ('ampoule', 'آمپول'), ('essence', 'اسنس'), ('makeup_remover', 'پاک\u200cکننده آرایش'), ('spot_patch', 'پچ ضدجوش')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='concerns_targeted',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-12 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
