# Generated by Django 5.2.1 on 2025-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_product_brand_en_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_types_en',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
