# Generated by Django 5.2.4 on 2025-07-12 15:00

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_product_skin_types_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_types_en',
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dry', 'خشک'), ('oily', 'چرب'), ('sensitive', 'حساس'), ('combination', 'مختلط'), ('normal', 'نرمال')], max_length=100),
        ),
    ]
