# Generated by Django 5.2.4 on 2025-07-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_product_skin_types_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
