# Generated by Django 5.2.4 on 2025-09-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
        ),
    ]
